GET http://localhost:5000/all

###
POST http://localhost:5000/create
Content-Type: application/json

{
    "title": "Third Blog",
    "content": "The third blog!"
}

###
GET http://localhost:5000/blog/1

###
DELETE http://localhost:5000/blog/66cea309adda8fb3c5a04abe

###
PUT http://localhost:5000/blog/66d54b5234fd663f54b470e1
Content-Type: application/json

{
    "title": "Another Blog",
    "content": "Edited blog",
    "author": "y1hua"
}

###
GET http://localhost:5000/user/all

###
POST http://localhost:5000/user/create
Content-Type: application/json

{
    "username": "y1hua",
    "password": "eva123456"
}