GET http://localhost:5000/all

###
POST http://localhost:5000/create
Content-Type: application/json

{
    "title": "Third Blog",
    "content": "The third blog!"
}

###
GET http://localhost:5000/blog/1

###
DELETE http://localhost:5000/blog/66d2dfe08e5dc24717db494c